CREATE TABLE sessions (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT,
  refresh_token VARCHAR(255) NOT NULL,
  user_agent VARCHAR(255) NOT NULL,
  client_ip VARCHAR(255) NOT NULL DEFAULT '0001-01-01 00:00:00Z', 
  is_blocked BOOLEAN NOT NULL DEFAULT false,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES users(id)
);