CREATE TABLE lovs (
  id BIGSERIAL PRIMARY KEY,
  group_key VARCHAR(255) NOT NULL,
  param_key VARCHAR(255) NOT NULL,
  param_description VARCHAR(255) NOT NULL,
  parent_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);

