version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=aksara2025
      - POSTGRES_DB=aksara
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

volumes:
  data-volume:
