version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: aksara-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aksara2025
      POSTGRES_DB: aksara
    ports:
      - "5432:5432"
    volumes:
      - ./data-aksara:/var/lib/postgresql/data
    restart: unless-stopped
