// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"
)

type EmployeeRoles struct {
	ID         int64        `json:"id"`
	EmployeeID int64        `json:"employee_id"`
	RoleID     int64        `json:"role_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

type Employees struct {
	ID                     int64          `json:"id"`
	UserID                 sql.NullInt64  `json:"user_id"`
	Fullname               sql.NullString `json:"fullname"`
	ResidentIdentityNumber sql.NullString `json:"resident_identity_number"`
	EmployeeIdentityNumber sql.NullString `json:"employee_identity_number"`
	Gender                 sql.NullInt16  `json:"gender"`
	Birthdate              sql.NullTime   `json:"birthdate"`
	Address                sql.NullString `json:"address"`
	Religion               sql.NullInt32  `json:"religion"`
	Birthday               sql.NullTime   `json:"birthday"`
	BirthPlace             sql.NullString `json:"birth_place"`
	Photo                  sql.NullString `json:"photo"`
	CreatedAt              sql.NullTime   `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	DeletedAt              sql.NullTime   `json:"deleted_at"`
}

type LocDistricts struct {
	ID         int32         `json:"id"`
	Name       string        `json:"name"`
	ProvinceID sql.NullInt32 `json:"province_id"`
	RegencyID  int32         `json:"regency_id"`
}

type LocProvinces struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type LocRegencies struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	ProvinceID int32  `json:"province_id"`
}

type Lovs struct {
	ID               int64         `json:"id"`
	GroupKey         string        `json:"group_key"`
	ParamKey         string        `json:"param_key"`
	ParamDescription string        `json:"param_description"`
	ParentID         sql.NullInt64 `json:"parent_id"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
}

type Offices struct {
	ID         int64          `json:"id"`
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	ProvinceID int32          `json:"province_id"`
	RegencyID  int32          `json:"regency_id"`
	DistrictID int32          `json:"district_id"`
	Email      string         `json:"email"`
	Phone      sql.NullString `json:"phone"`
	Address    sql.NullString `json:"address"`
	LogoUrl    sql.NullString `json:"logo_url"`
	CreatedBy  int64          `json:"created_by"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
}

type Schools struct {
	ID             int64          `json:"id"`
	Code           string         `json:"code"`
	Name           string         `json:"name"`
	IsPublicSchool bool           `json:"is_public_school"`
	OfficeID       sql.NullInt64  `json:"office_id"`
	ProvinceID     int32          `json:"province_id"`
	RegencyID      int32          `json:"regency_id"`
	DistrictID     int32          `json:"district_id"`
	Email          sql.NullString `json:"email"`
	Phone          sql.NullString `json:"phone"`
	Address        sql.NullString `json:"address"`
	LogoUrl        sql.NullString `json:"logo_url"`
	CreatedBy      int64          `json:"created_by"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type Sessions struct {
	ID           int64         `json:"id"`
	UserID       sql.NullInt64 `json:"user_id"`
	RefreshToken string        `json:"refresh_token"`
	UserAgent    string        `json:"user_agent"`
	ClientIp     string        `json:"client_ip"`
	IsBlocked    bool          `json:"is_blocked"`
	ExpiresAt    time.Time     `json:"expires_at"`
	CreatedAt    time.Time     `json:"created_at"`
}

type UserRoles struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Users struct {
	ID           int64         `json:"id"`
	Name         string        `json:"name"`
	Fullname     string        `json:"fullname"`
	Email        string        `json:"email"`
	Password     string        `json:"password"`
	UserRoleID   int32         `json:"user_role_id"`
	OfficeID     sql.NullInt64 `json:"office_id"`
	SchoolID     sql.NullInt64 `json:"school_id"`
	IsSuperAdmin sql.NullBool  `json:"is_super_admin"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
	DeletedAt    sql.NullTime  `json:"deleted_at"`
}
