// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: office.sql

package db

import (
	"context"
	"database/sql"
)

const createOffice = `-- name: CreateOffice :one
INSERT INTO offices (
  code,
  name,
  province_id,
  regency_id,
  district_id,
  email,
  phone,
  address,
  logo_url,
  created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, code, name, province_id, regency_id, district_id, email, phone, address, logo_url, created_by, created_at, updated_at, deleted_at
`

type CreateOfficeParams struct {
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	ProvinceID int32          `json:"province_id"`
	RegencyID  int32          `json:"regency_id"`
	DistrictID int32          `json:"district_id"`
	Email      string         `json:"email"`
	Phone      sql.NullString `json:"phone"`
	Address    sql.NullString `json:"address"`
	LogoUrl    sql.NullString `json:"logo_url"`
	CreatedBy  int64          `json:"created_by"`
}

func (q *Queries) CreateOffice(ctx context.Context, arg *CreateOfficeParams) (Offices, error) {
	row := q.db.QueryRowContext(ctx, createOffice,
		arg.Code,
		arg.Name,
		arg.ProvinceID,
		arg.RegencyID,
		arg.DistrictID,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.LogoUrl,
		arg.CreatedBy,
	)
	var i Offices
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ProvinceID,
		&i.RegencyID,
		&i.DistrictID,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.LogoUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteOffice = `-- name: DeleteOffice :execresult
UPDATE offices
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
AND deleted_at IS NULL
RETURNING id, code, name, province_id, regency_id, district_id, email, phone, address, logo_url, created_by, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteOffice(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOffice, id)
}

const getOfficeById = `-- name: GetOfficeById :one
SELECT  a.id, a.code, a.name, a.province_id, a.regency_id, a.district_id, a.email, a.phone, a.address, a.logo_url, a.created_by FROM offices a
WHERE a.id = $1 
AND a.deleted_at IS NULL 
LIMIT 1
`

type GetOfficeByIdRow struct {
	ID         int64          `json:"id"`
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	ProvinceID int32          `json:"province_id"`
	RegencyID  int32          `json:"regency_id"`
	DistrictID int32          `json:"district_id"`
	Email      string         `json:"email"`
	Phone      sql.NullString `json:"phone"`
	Address    sql.NullString `json:"address"`
	LogoUrl    sql.NullString `json:"logo_url"`
	CreatedBy  int64          `json:"created_by"`
}

func (q *Queries) GetOfficeById(ctx context.Context, id int64) (GetOfficeByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getOfficeById, id)
	var i GetOfficeByIdRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ProvinceID,
		&i.RegencyID,
		&i.DistrictID,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.LogoUrl,
		&i.CreatedBy,
	)
	return i, err
}

const listAllOffices = `-- name: ListAllOffices :many
SELECT a.id, a.code, a.name, a.province_id, a.regency_id, a.district_id, a.email, a.phone, a.address, a.logo_url, a.created_by, b.name as province, c.name as regency, d.name as district FROM offices a
JOIN loc_provinces b ON a.province_id = b.id
JOIN loc_regencies c ON a.regency_id = c.id
LEFT JOIN loc_districts d ON a.district_id = d.id
WHERE a.deleted_at IS NULL 
ORDER BY a.id
LIMIT $1 OFFSET $2
`

type ListAllOfficesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllOfficesRow struct {
	ID         int64          `json:"id"`
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	ProvinceID int32          `json:"province_id"`
	RegencyID  int32          `json:"regency_id"`
	DistrictID int32          `json:"district_id"`
	Email      string         `json:"email"`
	Phone      sql.NullString `json:"phone"`
	Address    sql.NullString `json:"address"`
	LogoUrl    sql.NullString `json:"logo_url"`
	CreatedBy  int64          `json:"created_by"`
	Province   string         `json:"province"`
	Regency    string         `json:"regency"`
	District   sql.NullString `json:"district"`
}

func (q *Queries) ListAllOffices(ctx context.Context, arg *ListAllOfficesParams) ([]ListAllOfficesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllOffices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllOfficesRow
	for rows.Next() {
		var i ListAllOfficesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ProvinceID,
			&i.RegencyID,
			&i.DistrictID,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.LogoUrl,
			&i.CreatedBy,
			&i.Province,
			&i.Regency,
			&i.District,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficesWithFilters = `-- name: ListOfficesWithFilters :many
SELECT a.id, a.code, a.name, a.province_id, a.regency_id, a.district_id, a.email, a.phone, a.address, a.logo_url, a.created_by, b.name as province, c.name as regency, d.name as district 
FROM offices a
JOIN loc_provinces b ON a.province_id = b.id
JOIN loc_regencies c ON a.regency_id = c.id
LEFT JOIN loc_districts d ON a.district_id = d.id
WHERE a.deleted_at IS NULL 
AND ($3::int IS NULL OR a.province_id = $3)
AND ($4::int IS NULL OR a.regency_id = $4)
AND ($5::int IS NULL OR a.district_id = $5)
AND ($6::text IS NULL OR a.name ILIKE '%' || $6 || '%')
ORDER BY a.id
LIMIT $1 OFFSET $2
`

type ListOfficesWithFiltersParams struct {
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	ProvinceID sql.NullInt32  `json:"province_id"`
	RegencyID  sql.NullInt32  `json:"regency_id"`
	DistrictID sql.NullInt32  `json:"district_id"`
	Name       sql.NullString `json:"name"`
}

type ListOfficesWithFiltersRow struct {
	ID         int64          `json:"id"`
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	ProvinceID int32          `json:"province_id"`
	RegencyID  int32          `json:"regency_id"`
	DistrictID int32          `json:"district_id"`
	Email      string         `json:"email"`
	Phone      sql.NullString `json:"phone"`
	Address    sql.NullString `json:"address"`
	LogoUrl    sql.NullString `json:"logo_url"`
	CreatedBy  int64          `json:"created_by"`
	Province   string         `json:"province"`
	Regency    string         `json:"regency"`
	District   sql.NullString `json:"district"`
}

// Optional province filter
// Optional regency filter
// Optional district filter
// Optional name search
func (q *Queries) ListOfficesWithFilters(ctx context.Context, arg *ListOfficesWithFiltersParams) ([]ListOfficesWithFiltersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOfficesWithFilters,
		arg.Limit,
		arg.Offset,
		arg.ProvinceID,
		arg.RegencyID,
		arg.DistrictID,
		arg.Name,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOfficesWithFiltersRow
	for rows.Next() {
		var i ListOfficesWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ProvinceID,
			&i.RegencyID,
			&i.DistrictID,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.LogoUrl,
			&i.CreatedBy,
			&i.Province,
			&i.Regency,
			&i.District,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalListAllOffices = `-- name: TotalListAllOffices :one
SELECT COUNT(*) as total_items FROM offices
WHERE deleted_at IS NULL
`

func (q *Queries) TotalListAllOffices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalListAllOffices)
	var total_items int64
	err := row.Scan(&total_items)
	return total_items, err
}

const totalListOfficesWithFilters = `-- name: TotalListOfficesWithFilters :one
SELECT COUNT(*) as total_items 
FROM offices a
WHERE a.deleted_at IS NULL 
AND ($1::int IS NULL OR a.province_id = $1)
AND ($2::int IS NULL OR a.regency_id = $2)
AND ($3::int IS NULL OR a.district_id = $3)
AND ($4::text IS NULL OR a.name ILIKE '%' || $4 || '%')
`

type TotalListOfficesWithFiltersParams struct {
	ProvinceID sql.NullInt32  `json:"province_id"`
	RegencyID  sql.NullInt32  `json:"regency_id"`
	DistrictID sql.NullInt32  `json:"district_id"`
	Name       sql.NullString `json:"name"`
}

// Optional province filter
// Optional regency filter
// Optional district filter
// Optional name search
func (q *Queries) TotalListOfficesWithFilters(ctx context.Context, arg *TotalListOfficesWithFiltersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalListOfficesWithFilters,
		arg.ProvinceID,
		arg.RegencyID,
		arg.DistrictID,
		arg.Name,
	)
	var total_items int64
	err := row.Scan(&total_items)
	return total_items, err
}

const updateOffice = `-- name: UpdateOffice :one
UPDATE offices
SET code = $1,
  name = $2,
  province_id = $3,
  regency_id = $4,
  district_id = $5,
  email = $6,
  phone = $7,
  address = $8,
  logo_url = $9,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $10
AND deleted_at IS NULL
RETURNING id, code, name, province_id, regency_id, district_id, email, phone, address, logo_url, created_by, created_at, updated_at, deleted_at
`

type UpdateOfficeParams struct {
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	ProvinceID int32          `json:"province_id"`
	RegencyID  int32          `json:"regency_id"`
	DistrictID int32          `json:"district_id"`
	Email      string         `json:"email"`
	Phone      sql.NullString `json:"phone"`
	Address    sql.NullString `json:"address"`
	LogoUrl    sql.NullString `json:"logo_url"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateOffice(ctx context.Context, arg *UpdateOfficeParams) (Offices, error) {
	row := q.db.QueryRowContext(ctx, updateOffice,
		arg.Code,
		arg.Name,
		arg.ProvinceID,
		arg.RegencyID,
		arg.DistrictID,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.LogoUrl,
		arg.ID,
	)
	var i Offices
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ProvinceID,
		&i.RegencyID,
		&i.DistrictID,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.LogoUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
