// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateOffice(ctx context.Context, arg CreateOfficeParams) (sql.Result, error)
	CreateSchool(ctx context.Context, arg CreateSchoolParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteOffice(ctx context.Context, id uint64) (sql.Result, error)
	DeleteSchool(ctx context.Context, id uint64) error
	DeleteUser(ctx context.Context, id uint64) error
	GetOffice(ctx context.Context, id uint64) (GetOfficeRow, error)
	GetSchool(ctx context.Context, id uint64) (School, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id uint64) (User, error)
	ListAllOffices(ctx context.Context, arg ListAllOfficesParams) ([]ListAllOfficesRow, error)
	ListAllSchools(ctx context.Context, arg ListAllSchoolsParams) ([]School, error)
	ListOfficesByDistrict(ctx context.Context, arg ListOfficesByDistrictParams) ([]Office, error)
	ListOfficesByProvince(ctx context.Context, arg ListOfficesByProvinceParams) ([]Office, error)
	ListOfficesByRegency(ctx context.Context, arg ListOfficesByRegencyParams) ([]Office, error)
	ListSchoolsByDistrict(ctx context.Context, arg ListSchoolsByDistrictParams) ([]School, error)
	ListSchoolsByOffice(ctx context.Context, arg ListSchoolsByOfficeParams) ([]School, error)
	ListSchoolsByProvince(ctx context.Context, arg ListSchoolsByProvinceParams) ([]School, error)
	ListSchoolsByRegency(ctx context.Context, arg ListSchoolsByRegencyParams) ([]School, error)
	LocationDistrictByRegency(ctx context.Context, arg LocationDistrictByRegencyParams) ([]LocDistrict, error)
	LocationProvince(ctx context.Context, arg LocationProvinceParams) ([]LocProvince, error)
	LocationRegencyByProvince(ctx context.Context, arg LocationRegencyByProvinceParams) ([]LocRegency, error)
	TotalListAllOffices(ctx context.Context) (int64, error)
	UpdateOffice(ctx context.Context, arg UpdateOfficeParams) (sql.Result, error)
	UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
