// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: school.sql

package db

import (
	"context"
	"database/sql"
)

const createSchool = `-- name: CreateSchool :execresult
INSERT INTO schools (
  id,
  code,
  name,
  office_id,
  province_id,
  regency_id,
  district_id,
  email,
  phone,
  address,
  logo_url,
  created_by
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSchoolParams struct {
	ID         uint64         `json:"id"`
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	OfficeID   uint64         `json:"office_id"`
	ProvinceID int32          `json:"province_id"`
	RegencyID  int32          `json:"regency_id"`
	DistrictID int32          `json:"district_id"`
	Email      sql.NullString `json:"email"`
	Phone      sql.NullString `json:"phone"`
	Address    sql.NullString `json:"address"`
	LogoUrl    sql.NullString `json:"logo_url"`
	CreatedBy  uint64         `json:"created_by"`
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSchool,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.OfficeID,
		arg.ProvinceID,
		arg.RegencyID,
		arg.DistrictID,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.LogoUrl,
		arg.CreatedBy,
	)
}

const deleteSchool = `-- name: DeleteSchool :exec
UPDATE schools
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) DeleteSchool(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteSchool, id)
	return err
}

const getSchool = `-- name: GetSchool :one
SELECT id, code, name, office_id, province_id, regency_id, district_id, email, phone, address, logo_url, created_by, created_at, updated_at, deleted_at FROM schools 
WHERE id = ? 
AND deleted_at IS NULL 
LIMIT 1
`

func (q *Queries) GetSchool(ctx context.Context, id uint64) (School, error) {
	row := q.db.QueryRowContext(ctx, getSchool, id)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.OfficeID,
		&i.ProvinceID,
		&i.RegencyID,
		&i.DistrictID,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.LogoUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllSchools = `-- name: ListAllSchools :many
SELECT id, code, name, office_id, province_id, regency_id, district_id, email, phone, address, logo_url, created_by, created_at, updated_at, deleted_at FROM schools
WHERE deleted_at IS NULL 
ORDER BY id
LIMIT ? OFFSET ?
`

type ListAllSchoolsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllSchools(ctx context.Context, arg ListAllSchoolsParams) ([]School, error) {
	rows, err := q.db.QueryContext(ctx, listAllSchools, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.OfficeID,
			&i.ProvinceID,
			&i.RegencyID,
			&i.DistrictID,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.LogoUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsByDistrict = `-- name: ListSchoolsByDistrict :many
SELECT id, code, name, office_id, province_id, regency_id, district_id, email, phone, address, logo_url, created_by, created_at, updated_at, deleted_at FROM schools
WHERE deleted_at IS NULL
AND district_id = ? 
ORDER BY id
LIMIT ? OFFSET ?
`

type ListSchoolsByDistrictParams struct {
	DistrictID int32 `json:"district_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListSchoolsByDistrict(ctx context.Context, arg ListSchoolsByDistrictParams) ([]School, error) {
	rows, err := q.db.QueryContext(ctx, listSchoolsByDistrict, arg.DistrictID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.OfficeID,
			&i.ProvinceID,
			&i.RegencyID,
			&i.DistrictID,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.LogoUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsByOffice = `-- name: ListSchoolsByOffice :many
SELECT id, code, name, office_id, province_id, regency_id, district_id, email, phone, address, logo_url, created_by, created_at, updated_at, deleted_at FROM schools
WHERE deleted_at IS NULL
AND office_id = ? 
ORDER BY id
LIMIT ? OFFSET ?
`

type ListSchoolsByOfficeParams struct {
	OfficeID uint64 `json:"office_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListSchoolsByOffice(ctx context.Context, arg ListSchoolsByOfficeParams) ([]School, error) {
	rows, err := q.db.QueryContext(ctx, listSchoolsByOffice, arg.OfficeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.OfficeID,
			&i.ProvinceID,
			&i.RegencyID,
			&i.DistrictID,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.LogoUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsByProvince = `-- name: ListSchoolsByProvince :many
SELECT id, code, name, office_id, province_id, regency_id, district_id, email, phone, address, logo_url, created_by, created_at, updated_at, deleted_at FROM schools
WHERE deleted_at IS NULL
AND province_id = ? 
ORDER BY id
LIMIT ? OFFSET ?
`

type ListSchoolsByProvinceParams struct {
	ProvinceID int32 `json:"province_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListSchoolsByProvince(ctx context.Context, arg ListSchoolsByProvinceParams) ([]School, error) {
	rows, err := q.db.QueryContext(ctx, listSchoolsByProvince, arg.ProvinceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.OfficeID,
			&i.ProvinceID,
			&i.RegencyID,
			&i.DistrictID,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.LogoUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsByRegency = `-- name: ListSchoolsByRegency :many
SELECT id, code, name, office_id, province_id, regency_id, district_id, email, phone, address, logo_url, created_by, created_at, updated_at, deleted_at FROM schools
WHERE deleted_at IS NULL
AND regency_id = ? 
ORDER BY id
LIMIT ? OFFSET ?
`

type ListSchoolsByRegencyParams struct {
	RegencyID int32 `json:"regency_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListSchoolsByRegency(ctx context.Context, arg ListSchoolsByRegencyParams) ([]School, error) {
	rows, err := q.db.QueryContext(ctx, listSchoolsByRegency, arg.RegencyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.OfficeID,
			&i.ProvinceID,
			&i.RegencyID,
			&i.DistrictID,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.LogoUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchool = `-- name: UpdateSchool :execresult
UPDATE schools
SET code = ?,
  name = ?,
  office_id = ?,
  province_id = ?,
  regency_id = ?,
  district_id = ?,
  email = ?,
  phone = ?,
  address = ?,
  logo_url = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSchoolParams struct {
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	OfficeID   uint64         `json:"office_id"`
	ProvinceID int32          `json:"province_id"`
	RegencyID  int32          `json:"regency_id"`
	DistrictID int32          `json:"district_id"`
	Email      sql.NullString `json:"email"`
	Phone      sql.NullString `json:"phone"`
	Address    sql.NullString `json:"address"`
	LogoUrl    sql.NullString `json:"logo_url"`
	ID         uint64         `json:"id"`
}

func (q *Queries) UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSchool,
		arg.Code,
		arg.Name,
		arg.OfficeID,
		arg.ProvinceID,
		arg.RegencyID,
		arg.DistrictID,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.LogoUrl,
		arg.ID,
	)
}
