// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: location.sql

package db

import (
	"context"
)

const locationDistrictByRegency = `-- name: LocationDistrictByRegency :many
SELECT id, name, province_id, regency_id FROM loc_districts
WHERE regency_id = ?
`

func (q *Queries) LocationDistrictByRegency(ctx context.Context, regencyID int32) ([]LocDistrict, error) {
	rows, err := q.db.QueryContext(ctx, locationDistrictByRegency, regencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocDistrict{}
	for rows.Next() {
		var i LocDistrict
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProvinceID,
			&i.RegencyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationProvince = `-- name: LocationProvince :many
SELECT id, name FROM loc_provinces
`

func (q *Queries) LocationProvince(ctx context.Context) ([]LocProvince, error) {
	rows, err := q.db.QueryContext(ctx, locationProvince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocProvince{}
	for rows.Next() {
		var i LocProvince
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationRegencyByProvince = `-- name: LocationRegencyByProvince :many
SELECT id, name, province_id FROM loc_regencies 
WHERE province_id = ?
`

func (q *Queries) LocationRegencyByProvince(ctx context.Context, provinceID int32) ([]LocRegency, error) {
	rows, err := q.db.QueryContext(ctx, locationRegencyByProvince, provinceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocRegency{}
	for rows.Next() {
		var i LocRegency
		if err := rows.Scan(&i.ID, &i.Name, &i.ProvinceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
